output:
  folder: /home/wasim/opensource/personal/cmwatcher-sidecar/test
  folderAnnotation:

kubeconfig: /home/wasim/.kube/config
namespace: default

resource:
  type: configmap
  labels:
   - name: findme1
     value:
     script:
     request:
      url: http://localhost:8080/hello
      method:
      payload:
      basicAuth:
        username:
        password:
   - name: findme2
     value:
     script:
     request:
      url:
      method:
      payload:
      basicAuth:
        username:
        password:
     